[package]
name = "netscaler_scales"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
futures = "0.3.31"
reqwest = "0.12.23"
tokio = { version = "1.47.1", features = ["full"] }
x509-parser = "0.18.0"
